FROM jenkins/jenkins:lts

# Muda para root para conseguir instalar pacotes no Linux do container
USER root

# Instala as dependências e o Docker CLI (Client)
RUN curl -fsSL -O https://download.docker.com/linux/static/stable/x86_64/docker-25.0.3.tgz && \
    tar xzvf docker-25.0.3.tgz && \
    mv docker/docker /usr/local/bin/ && \
    rm -rf docker docker-25.0.3.tgz

# Retorna para o usuário padrão do Jenkins
USER jenkins